"""add template to evento

Revision ID: 27a2c5a3caa3
Revises: 53d009f4f754
Create Date: 2026-02-28 11:32:24.871491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a2c5a3caa3'
down_revision = '53d009f4f754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column( sa.Column('template', sa.String(length=50), nullable=False, server_default='classic') )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('template')

    # ### end Alembic commands ###
