"""initial migration

Revision ID: 45e556b141da
Revises: 
Create Date: 2026-02-17 18:18:35.504468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e556b141da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('lugar', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('mensaje_principal', sa.Text(), nullable=True),
    sa.Column('imagen_portada', sa.String(length=250), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('confirmaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('asiste', sa.Boolean(), nullable=False),
    sa.Column('mensaje', sa.String(length=300), nullable=True),
    sa.Column('fecha_confirmacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmaciones')
    op.drop_table('eventos')
    # ### end Alembic commands ###
