"""creacion base de datos limpia

Revision ID: 780a2dbfad47
Revises: 
Create Date: 2026-06-04 10:50:03.284082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780a2dbfad47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=False),
    sa.Column('codigo_verificacion', sa.String(length=6), nullable=True),
    sa.Column('codigo_expiracion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('lugar', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('mensaje_principal', sa.Text(), nullable=True),
    sa.Column('imagen_portada', sa.String(length=250), nullable=True),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('template', sa.String(length=50), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('status_pago', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('confirmaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('asiste', sa.Boolean(), nullable=False),
    sa.Column('mensaje', sa.String(length=300), nullable=True),
    sa.Column('fecha_confirmacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evento_cronograma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagenes_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagenes_evento')
    op.drop_table('evento_cronograma')
    op.drop_table('confirmaciones')
    op.drop_table('eventos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
