"""agrega campos de pago mercado pago

Revision ID: efd6ca7b3155
Revises: f74aae8cbd25
Create Date: 2026-04-30 10:21:02.979925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd6ca7b3155'
down_revision = 'f74aae8cbd25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status_pago', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('status_pago')
        batch_op.drop_column('payment_id')
        batch_op.drop_column('pagado')

    # ### end Alembic commands ###
